### ISSUE TITLE
Needs assessment surveys

### ISSUE THREAD

**Issue by seamustuohy** [OpenInternet/co-pilot#1]
Needs Assessment will be conducted a survey of digital security trainers.

Includeing:
- Circumvention tools being trained on.
- Circumvention tools that are currently difficult to train on, or assess user understanding of.
- Circumvention tools which might benefit from hands on practice.
- Interest in using a tool like co-pilot.
- Concerns about adding training technology into their existing practice.

**Comment by seamustuohy** [comment]
Created a [wiki page](https://github.com/OpenInternet/co-pilot/wiki/Needs-Assessment-Survey) to place needs assessment survey.

**Comment by seamustuohy** [comment]
Making each trainer answer questions about every tool they use might make us lose some of the responses. I am thinking we should make it one set of questions about all tools that hands on training is done on.

e.g.
how many people?
ideal # of people?
average % of time doing hands on vs. lecture.

**Comment by seamustuohy** [comment]
Currently working on a google form for this. WIll share the link internally once I get the markdown questions into the form.

**Comment by seamustuohy** [comment]
TODO still on the form:
- [x] Create paths so that people only fill out what is relevant
- [x] Create introductory text
- [x] Create explanatory co-pilot text
- [x] Add OPTIONAL demographic information
- [x] Write invitation e-mail

**Comment by megdeb** [comment]
added text here (https://github.com/OpenInternet/co-pilot/wiki/Needs-Assessment-Survey)

**Comment by megdeb** [comment]
Held a team brainstorm of trainers we would like to send the survey to (over 41 potential trainers). Will create a short-list with @elationfoundation and will begin drafting email to trainers.

**Comment by megdeb** [comment]
Completed the draft email and sent over to @elationfoundation . Will work together to determine who from the team will be emailing which trainers, in order to benefit from existing relationships certain team members have in the community.

**Comment by megdeb** [comment]
Began sending out emails to trainers asking to complete the online needs assessment survey.

**Comment by megdeb** [comment]
First three responses in!

**Comment by megdeb** [comment]
Jon Camfield: 

Ditto (sending emails)

**Comment by megdeb** [comment]
Received 11 responses so far from trainers. All have agreed to be contacted for follow-up interviews.

**Comment by megdeb** [comment]
https://chart.googleapis.com/chart?cht=p&chs=345x150&chl=Yes%20%5B13%5D%7CNo%20%5B0%5D&chco=0000e0&chd=e%3A..AA

**Comment by megdeb** [comment]
Number of trainers who agreed to be contacted for follow-up questions:

![All 13 trainers agreed for follow-up!](https://cloud.githubusercontent.com/assets/8431674/5726485/a067f84a-9b29-11e4-840c-69fe9b8e104f.png)

**Comment by megdeb** [comment]
The initial needs assessment survey has been completed. 20 experienced digital security trainers who are well known and trusted in the community have provided feedback for the Co-Pilot project. All trainers have agreed to follow up interviews.
