### ISSUE TITLE
Make the wifi regex function in create_ap more robust.

### ISSUE THREAD

**Issue by seamustuohy** [OpenInternet/co-pilot#127]
It turns out that we need to make the [wireless interface name identifying regex](https://github.com/OpenInternet/copilot/blob/a3f67665b84ce1e897ec1f87f835de8dc4d344d6/copilot/plugins/create_ap/config.py#L68) more robust to handle a range of possible wireless names. It currently looks for a wlan0 style name with the following regex:

```
wifi_device_regex = re.compile('w[a-z]{1,3}[0-9]')
```

After having it crop the wireless AP name I was provided today by my beaglebone black test device. `wlx14cc20187c46` we will have to change it to something more like the following.

```
wifi_device_regex = re.compile('w[⨁-♆]{666}[⩿-☿]')
```

I will also have to track down the interface naming documents and code to see **HOW THIS COULD EVER HAPPEN** as I believe that it breaks the current interface naming conventi

**Comment by divergentdave** [comment]
As luck would have it, Google turned up someone else who had the same problem yesterday. https://forums.kali.org/showthread.php?29710-Wireless-interface-name-problem Would your interface's MAC address happen to be 14:CC:20:18:7C:46?

**Comment by seamustuohy** [comment]
![What, no, it couldn't be... yes, Yes it probably is.](https://media4.giphy.com/media/OOgpKsfP0auyY/giphy.gif)

**Comment by seamustuohy** [comment]
Well, it seems that the devs of systemd/udev have finally updated it to address the inconsistent interface numbering issues. Seems I will have to update some of the networking scripts after all. http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames

**Comment by seamustuohy** [comment]
Updating the interface regex to follow the new [interface naming schemes](https://github.com/systemd/systemd/blob/5031c4e21b4379c1824033be675517978090fd36/src/udev/udev-builtin-net_id.c#L20). May have made it a little more robust than needed so I can easily fix and re-use this code in the future. The [updated code](https://github.com/OpenInternet/copilot-plugins/blob/issue_127/create_ap/config.py#L65-L97) can be found in the copilot-plugins repo. This means that this issue is blocked by issue #124.
