### ISSUE TITLE
Develop wire frames for UI

### ISSUE THREAD

**Issue by megdeb** [OpenInternet/co-pilot#18]
**Develop wire frames for User Interface**
- Simple wire frames of the user interface will be developed by @elationfoundation in order to get a sense of the flow of the design. 
- After initial review, wire frames will be sent over to @megdeb, reviewed, printed and used in UI design interviews

**Comment by seamustuohy** [comment]
Wire frames updated:

### Save Profile Page
- [SVG](https://raw.github.com/wiki/openinternet/co-pilot/images/flow_chart.save.profile.svg)
- [PDF](https://raw.github.com/wiki/openinternet/co-pilot/images/flow_chart.save.profile.pdf)
- [PNG](https://raw.github.com/wiki/openinternet/co-pilot/images/flow_chart.save.profile.png)

### Load Profile Page
- [SVG](https://raw.github.com/wiki/openinternet/co-pilot/images/flow_chart.load.profile.svg)
- [PDF](https://raw.github.com/wiki/openinternet/co-pilot/images/flow_chart.load.profile.pdf)
- [PNG](https://raw.github.com/wiki/openinternet/co-pilot/images/flow_chart.load.profile.png)

### Persistant Warnings
- [SVG](https://raw.github.com/wiki/openinternet/co-pilot/images/flow_chart.warnings.persistant.svg)
- [PDF](https://raw.github.com/wiki/openinternet/co-pilot/images/flow_chart.warnings.persistant.pdf)
- [PNG](https://raw.github.com/wiki/openinternet/co-pilot/images/flow_chart.warnings.persistant.png)

### Tutorial Page
- [SVG](https://raw.github.com/wiki/openinternet/co-pilot/images/tutorial.svg)
- [PDF](https://raw.github.com/wiki/openinternet/co-pilot/images/tutorial.pdf)
- [PNG](https://raw.github.com/wiki/openinternet/co-pilot/images/tutorial.png)

### Configuration Page
- [SVG](https://raw.github.com/wiki/openinternet/co-pilot/images/config.svg)
- [PDF](https://raw.github.com/wiki/openinternet/co-pilot/images/config.pdf)
- [PNG](https://raw.github.com/wiki/openinternet/co-pilot/images/config.png)

### Password Page
- [SVG](https://raw.github.com/wiki/openinternet/co-pilot/images/password.svg)
- [PDF](https://raw.github.com/wiki/openinternet/co-pilot/images/password.pdf)
- [PNG](https://raw.github.com/wiki/openinternet/co-pilot/images/password.png)

**Comment by megdeb** [comment]
Reviewed wire frames with @elationfoundation and identified adjustments that need to be made before UI testing begins next week.

**Comment by seamustuohy** [comment]
Wireframes were re-worked and updated.
