### ISSUE TITLE
Schedule Follow-up Interviews with Survey Participants

### ISSUE THREAD

**Issue by megdeb** [OpenInternet/co-pilot#19]
List of potential interviewees includes: 2, 5, 9, 16

**Comment by megdeb** [comment]
@elationfoundation please confirm the participants chosen above for follow-up interviews. If you feel anyone else should be added, please let me know.

**Comment by megdeb** [comment]
Doodle poll has been created to begin scheduling interviews.

**Comment by seamustuohy** [comment]
List looks good.

**Comment by megdeb** [comment]
2 and 5 have been scheduled for tomorrow. will review format with you tomorrow at our meeting.

**Comment by megdeb** [comment]
9 has been scheduled for Friday

**Comment by megdeb** [comment]
two down ... two to go! lots of great feedback/ideas from both trainers with extensive experience in the field!

**Comment by megdeb** [comment]
All formal follow up interviews have taken place and will begin write-up.

**Comment by megdeb** [comment]
All interviews have been scheduled.
