### ISSUE TITLE
Write-up Summary Report of Initial Survey Results

### ISSUE THREAD

**Issue by megdeb** [OpenInternet/co-pilot#21]
Draft of initial survey results has been completed. Will work on polishing this draft today and tomorrow. :bowtie:

**Comment by megdeb** [comment]
draft completed and sent over to @elationfoundation

**Comment by megdeb** [comment]
Thorough review and revisions have taken place. Final is ready for final review and submission.

**Comment by seamustuohy** [comment]
Report is completed and can be found on the [wiki](https://github.com/OpenInternet/co-pilot/wiki/Needs-Assessment-Survey).
