### ISSUE TITLE
Prioritize UI Interviews - Iteration One

### ISSUE THREAD

**Issue by megdeb** [OpenInternet/co-pilot#22]
Identification of interviewees for the user interface design is under way.

**Comment by megdeb** [comment]
2 internal interviews have been scheduled for tomorrow to review/practice the wire frame interview.

**Comment by seamustuohy** [comment]
Are these all completed?

**Comment by megdeb** [comment]
First iteration of UI interviews have been completed. Write-up and outcomes will be placed in Think Aloud Testing Outcomes Document #33
