### ISSUE TITLE
Add "Tor" switch so participants' traffic is encrypted when passively using the Internet during training session

### ISSUE THREAD

**Issue by megdeb** [OpenInternet/co-pilot#26]
During a follow up interview, one trainer suggested making a "Tor" switch so the trainer can choose when to send all traffic through the Tor network. This is so when participants are passively connecting to the Internet during a training session - checking email, news, social media, etc - the connection is encrypted and more anonymous. Once the trainer goes to use Co-Pilot profiles to block and censor, they would be able to turn this feature off so connection speeds will be faster.

**Comment by megdeb** [comment]
Further exploration must be done in order to understand if this feature would be useful for other trainers in different contexts. For example, if most trainers are under the assumption they are going to have low bandwidth and connectivity, Tor would only exacerbate the slow connection speed.

**Comment by seamustuohy** [comment]
I agree, this is a out of scope for the prototype. It is an interesting idea. It could be done by building off existing projects like [portal[(https://github.com/grugq/PORTALofPi)  if anyone is interested in exploring it in the future.

**Comment by seamustuohy** [comment]
Closed as out of scope.
