### ISSUE TITLE
Write-up for the follow up interviews

### ISSUE THREAD

**Issue by megdeb** [OpenInternet/co-pilot#27]
This write-up will be a condensed version of main takeaways from the follow up interviews that took place in Feb.

**Comment by megdeb** [comment]
### Rough overview of follow up interviews

**Profiles**
- sharing profiles is necessary; and a way to centralize profiles that trainers are creating
- need to be able to easily and quickly switch from one scenario to another
- profiles to mimic different country environments is useful
- pre-loaded profiles for specific countries

**Verification of tool**
- highly useful for participants to verify tool is working and will work in local environment

**Throttling-specific (varied by trainer)**
- useful for specific cases
- helpful in mimicking the home environment if bandwidth at training location is significantly different
  - helps avoid the “bait and switch situation”
  - accurate expectations for tool’s abilities in home environment

**Ethernet**
- most concerned if there was a work around if Ethernet connection is not readily available

**Documentation**
- explanatory material on basic concepts for the non-technical trainer is necessary (e.g. basic protocol knowledge, http vs https, additional technical terms, etc)
- specific use-cases and examples
- generic curriculum built-out

**Comment by seamustuohy** [comment]
Issues have been created for all interview responses that can be implemented.
