### ISSUE TITLE
Needs Assessment Interviews

### ISSUE THREAD

**Issue by seamustuohy** [OpenInternet/co-pilot#3]
Needs Assessment Interviews with trainers will guide the development of rough interface prototypes. The interviewees will be chosen from survey participants.

**Comment by megdeb** [comment]
Held a team brainstorm of trainers we would like to send the survey to (over 41 potential trainers). Will create a short-list with @elationfoundation and will begin drafting email to trainers.

**Comment by megdeb** [comment]
Completed the draft email and sent over to @elationfoundation . Will work together to determine who from the team will be emailing which trainers, in order to benefit from existing relationships certain team members have in the community.

**Comment by megdeb** [comment]
Began sending out emails to trainers asking to complete the online needs assessment survey.

**Comment by megdeb** [comment]
First three responses in!

**Comment by joncamfield** [comment]
Ditto (sending emails)

**Comment by megdeb** [comment]
Received 11 responses so far from trainers. All have agreed to be contacted for follow-up interviews.

**Comment by megdeb** [comment]
All interviews have been completed and write-up is underway.
