### ISSUE TITLE
Feature request - ability to save profiles directly on co-pilot

### ISSUE THREAD

**Issue by megdeb** [OpenInternet/co-pilot#41]
During the think aloud testing interviews, several trainers wanted the ability to not only save profiles to a USB, but also be able to save straight to Co-Pilot's SD card.

**Comment by seamustuohy** [comment]
Currently implementing save functionality. Will be implemented as follows.
- User hits SAVE:
- profile is saved in temporary save location
- User is taken to an interstitial page where they can choose USB or On Device
- User clicks USB or On Device
- Profile is saved to that location
- User is taken back to the profile editing page

**Comment by seamustuohy** [comment]
This was completed a while ago actually.
