### ISSUE TITLE
Trainer Documentation

### ISSUE THREAD

**Issue by seamustuohy** [OpenInternet/co-pilot#8]
Documentation to show a trainer  how to use the tool

**Comment by seamustuohy** [comment]
Per the initial user assessment survetsurvey:

I would like "explanatory materials on the different environments and types of blocking, real-world examples where they have been used."

**Comment by megdeb** [comment]
Real-world examples from multiple regions may be especially beneficial.

**Comment by megdeb** [comment]
#28 is an example of some of the documentation that will need to be developed for Co-Pilot

**Comment by seamustuohy** [comment]
Per: https://github.com/OpenInternet/co-pilot/issues/27
- explanatory material on basic concepts for the non-technical trainer is necessary (e.g. basic protocol knowledge, http vs https, additional technical terms, etc)
- specific use-cases and examples
- generic curriculum built-out

**Comment by seamustuohy** [comment]
[Completed and located on the wiki.](https://github.com/OpenInternet/co-pilot/wiki/Setup-Guide)
